#!/bin/bash
# Quick Reference: SerpAPI + Viincci-RAG Setup

echo "🎯 QUICK REFERENCE CARD"
echo "======================="
echo ""
echo "📍 Files:"
echo "  .env                    — Your API key (NOT pushed to GitHub) ✓"
echo "  .env.example            — Template for other developers"
echo "  generate_davinci.py     — Script to generate content"
echo "  da_vinci_history.txt    — Generated article (8 sources)"
echo "  SERPAPI_SETUP.md        — Full setup documentation"
echo ""
echo "🚀 Quick Commands:"
echo "  python generate_davinci.py           # Generate da Vinci content"
echo "  jupyter notebook viincci_rag/examples/test_examples.ipynb"
echo ""
echo "🔑 API Key:"
echo "  Status: ✓ Loaded from .env"
echo "  File: .env (ignored by Git)"
echo "  Length: 64 characters"
echo "  Credits: 250/month (free tier)"
echo ""
echo "📊 Last Generated:"
echo "  Topic: Leonardo da Vinci biography"
echo "  Results: 8 sources"
echo "  Size: 2,557 characters"
echo "  Timestamp: $(date)"
echo ""
echo "🔐 Security:"
echo "  ✓ .env is in .gitignore"
echo "  ✓ API key never committed"
echo "  ✓ Safe to push to GitHub"
echo ""
echo "📚 Resources:"
echo "  SerpAPI Dashboard: https://serpapi.com/dashboard"
echo "  Setup Guide: cat SERPAPI_SETUP.md"
echo "  Examples: viincci_rag/examples/README.md"
